Revert "Revert main merge"
This reverts commit 94f2afb2e6b2f212c5ba6df7878bf46b6429b7c4.

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -1,4 +1,4 @@
-name: ESLint check
+name: Lint code
 
 on:
   workflow_call:
@@ -7,13 +7,8 @@ on:
     branches-ignore: [staging, production]
     paths: ['**.js', '**.ts', '**.tsx', '**.json', '**.mjs', '**.cjs', 'config/.editorconfig', '.watchmanconfig', '.imgbotconfig']
 
-concurrency:
-  group: ${{ github.ref == 'refs/heads/main' && format('{0}-{1}', github.ref, github.sha) || github.ref }}-lint
-  cancel-in-progress: true
-
 jobs:
   lint:
-    name: ESLint check
     if: ${{ github.actor != 'OSBotify' || github.event_name == 'workflow_call' }}
     runs-on: ubuntu-latest
     steps:
@@ -27,3 +22,16 @@ jobs:
         run: npm run lint
         env:
           CI: true
+
+      - name: Verify there's no Prettier diff
+        run: |
+          npm run prettier -- --loglevel silent
+          if ! git diff --name-only --exit-code; then
+            # shellcheck disable=SC2016
+            echo 'Error: Prettier diff detected! Please run `npm run prettier` and commit the changes.'
+            exit 1
+          fi
+
+      - name: Run unused style searcher
+        shell: bash
+        run: ./.github/scripts/findUnusedKeys.sh
